title: George Carvalho
author: George Carvalho
email: geocarvalho91@gmail.com
description: >-
  Healthcare Data Scientist and Bioinformatician portfolio and blog. Projects, experience, and thoughts on technology.
baseurl: ""
url: "https://geocarvalho.github.io"
github_username: geocarvalho

header_pages:
  - about.md
  - projects.md
  - experience.md
  - blog.md
  - contact.md

# Build settings
theme: minima
plugins:
  - jekyll-feed
