title: George Carvalho
description: >-
  Healthcare Data Scientist and Bioinformatician portfolio and blog. Projects, experience, and thoughts on technology.
baseurl: ""
url: "https://geocarvalho.github.io"
github_username: geocarvalho
linkedin_username: george-carvalho

header_pages:
  - about.md
  - projects.md
  - experience.md
  - blog.md
  - contact.html

# Build settings
theme: minima
plugins:
  - jekyll-feed
